# General
name: "Jessica Howe"
description: "Accounting & Tax Professional"
url: https://www.howe.tax

markdown: kramdown
highlighter: rouge

paginate: 5
permalink: /:title
singlepage: resume

# Social share and comments.
#twitter: username
#githubname: username
#google: +username
linkedin: jessicaehowe
#scholar: userid
email: jessica@howe.tax

# RSS feed
rss-feed-limit: 10
rss-show-full: "no"
