# General
name: "Jessica Howe"
description: "Tax Professional"
url: http://www.howe.tax

markdown: redcarpet
highlighter: pygments

paginate: 5
permalink: /:title
singlepage: resume

# Social share and comments.
twitter: stephengroat
#github: stephengroat
#google: +stephengroat
#linkedin: sgroat
#scholar: 2FxnwFgAAAAJ
#email: stephen@egroat.com

# RSS feed
rss-feed-limit: 10
rss-show-full: "no"
