# General
name: "Jessica Howe"
description: "Tax Professional"
url: http://www.howe.tax

markdown: redcarpet
highlighter: pygments

paginate: 5
permalink: /:title
singlepage: resume

# Social share and comments.
#twitter: username
#githubname: username
#google: +username
#linkedin: username
#scholar: userid
email: jessica@howe.tax

# RSS feed
rss-feed-limit: 10
rss-show-full: "no"
